### ISSUE TITLE
Pipe separator not working 

### ISSUE THREAD

**Issue by sbugliarisi** [wizzomafizzo/tapto#16]
I received an NFC device from grumpyoldgamer and it’s working beautifully, I’ve got it in the PC Engine style 3D case and I’m really loving it! 

I'm able to successfully switch ini’s using **ini:3 but when I try to run it with another command e.g. **ini:3||_Console/SNES it doesn’t work. The second command works fine by itself but putting them both together doesn’t work for me.  

I also noticed if I use the taptui script and try to chain the ini switch to something else it writes an incorrect string to the card (the ini number is missing), e.g. **ini:||_Console/SNES

I hope I’m not doing something stupid or missing something, I’m wondering if that’s the case because I didn’t see these issues reported by anyone else

**Comment by sigboe** [comment]
@wizzomafizzo note this is not a bug in taptui as if you read quickly you might glance over the fact that loading ini does indeed work for him. 

@sbugliarisi thank you for bringing to light this issue with taptui and the radiobuttons to select the ini. This is a quirk with the ui toolkit, it is not abovious that you need to select the radio button before you proceed. It is not enough to just highlight it and continue with OK, you actually need to select it. (as I have been on an temporary hiatus and is slowly coming back) I don't remember the button on the gamepad you have to use. But using a keyboard it is space. There is a corresponding button on the gamepad to press space (courtesy of the MiSTer team). You will see when a radio button is selected
![image](https://github.com/wizzomafizzo/tapto/assets/2087930/1f2cb120-4d16-4479-b24d-467d080c5ca1)

I will put it on my todo list to add a dialog to make sure that the user understands how to use this radio button UI widget, and note which key to press on either gamepad or keyboard (mouse also works, only over ssh if your terminal supports it). 

@sbugliarisi you didn't do anything wrong, it's just the UI toolkit that isn't as obvious, and I will make it more obvious

**Comment by sbugliarisi** [comment]
Thanks for the detailed explanation @sigboe, I tried using a keyboard and I see that the command is correctly written to the card now. 

But I’m still having an issue, when I write a card with 2 commands together the card doesn’t work. I just wrote **ini:2||_Arcade/Ms. Pac-Man.mra to a card and it doesn’t load the core. I get a message on screen “NO RBF FOUND”. If I write _Arcade/Ms. Pac-Man.mra to the card it works perfectly and loads the core. Any idea what might be causing this issue?

**Comment by sigboe** [comment]
@sbugliarisi i am not sure, @wizzomafizzo might know, but I presume that it is trying to launch the game to quickly after changing the ini, so mister is not ready to take the next command yet

**Comment by wizzomafizzo** [comment]
I agree this is what's probably happening but I can't test for a couple weeks. Well probably have to hardcode a delay. A manual delay could be a good new command too

**Comment by wizzomafizzo** [comment]
It is working now. I will include this fix in the next release. Nice and smooth now the ini change is instant and seamless

**Comment by sigboe** [comment]
@sbugliarisi I have also made the menu for selecting ini files not able to select no ini files. simply by pre selecting ini 1

There is still the issue that most people dont know they need to press a different button to select a new ini file than to continue with the ini file already selected

I forgot to write here about it
