### ISSUE TITLE
exit_game should not relaunch the menu if no game was launched

### ISSUE THREAD

**Issue by wizzomafizzo** [wizzomafizzo/tapto#25]
If exit_game is enabled, once a card is removed, it will relaunch the menu core ("exit the core") no matter what command the card has launched. This is awkward if you have the option enabled, scan a card which launches a shell command only, then it will restart the menu core for no reason afterwards.

During the processing of commands the cmdenv state should track if a core or game launch has occurred, and only launch the menu core if so.

**Comment by asturur** [comment]
i can try to take this if you are not working on it already

**Comment by asturur** [comment]
this is sovled
