### ISSUE TITLE
TapToUI: Linked File Path Selection Fails to Trigger Write Screen

### ISSUE THREAD

**Issue by spark2k06** [wizzomafizzo/tapto#40]
TapToUI does not allow you to write a file that links to another file, e.g. an MRA that is a link to another MRA.

That is, when you select it, it prompts you to select whether you want it to use its linked file or the path of the link itself. The first one works, the second one simply doesn't do anything, the screen that allows you to write to the card doesn't appear.

**Comment by sigboe** [comment]
fixed https://github.com/wizzomafizzo/tapto/commit/44202f0ec3e66179ec25f30c9bc57d6fb82a1f5c

Thanks for bringing this to my attention.

Bonus feature: Now it defaults to the shortest of the two if you just pick what it suggests
