### ISSUE TITLE
With version 1.3, I cannot scan the same card after exiting back to the MiSTer main menu.

### ISSUE THREAD

**Issue by NML32** [wizzomafizzo/tapto#49]
With version 1.3, I cannot scan the same card after exiting back to the MiSTer main menu.

Recreate issue
Launch a game or core from the NFC reader attached to the MiSTer
Exit back to MiSTer Main Menu. Shift+Ctrl+Alt+Alt
Launch the same card
Nothing happens.

**Comment by asturur** [comment]
Since i made the timeout change and the card shuffling change i ll probably should check this. I could have make some normal flow unusable.

Can you list your ini configuration here please?

**Comment by NML32** [comment]
[tapto]
connection_string=""
allow_commands=yes
disable_sounds=no
probe_device=yes
exit_game=no
exit_game_blocklist=
exit_game_delay=0
debug=no
