### ISSUE TITLE
Enhancement: Add option to manage entries for the API port in /media/fat/linux/iptables.up.rules

### ISSUE THREAD

**Issue by Kreeblah** [wizzomafizzo/tapto#50]
I just saw the news about the new TapTo Life app, and wanted to give it a try, but because I use the `security_fixes.sh` script, I'm using the built-in `iptables` firewall on my MiSTer.  So, in order to be able to access the API, I had to look through the source to find what port it runs on and write a rule for that.

It would be nice if `taptui.sh` had an option to do that for me, especially since I need to re-run the script after every Linux update (which means I'll need to re-add the `iptables` entry after each Linux update as well).

For reference, all I had to add was this:

```
# Allow TapTo connections
-A INPUT -p tcp -m state --state NEW --dport 7497 -j ACCEPT
```

It just needs to be before the lines that send things to the `REJECT` target.

**Comment by sigboe** [comment]
I kind of think this maybe should be added to the documentation, but I don't know if we should handle it directly. Unless Wizzo wants me to add it to TAPTUI.

Maybe I should make a GUI to add and remove firewall rules and donate it to the repo that maintains security_fixes.sh, In that case I would have to add it to my TODO list and not forget about it!

**Comment by sigboe** [comment]
Opened a PR at the script that manages iptables
https://github.com/MiSTer-devel/Scripts_MiSTer/pull/114
