### ISSUE TITLE
[Bug] Issue with custom color setting in the online bulk label generator

### ISSUE THREAD

**Issue by TheTrainGoes** [wizzomafizzo/tapto#53]
https://tapto-designer.netlify.app/

Bug:  
There is an issue with custom color setting in the online bulk label generator.

Expected:
When setting a custom color value I should be able to type out the numbers.

Actual:
Pressing any key (backspace or number keys) causes the pop-up to disappear.  That single change will be saved but I will need to return to the pop-up to enter the next character.

Example:
Changing the color white (255,255,255) to another value would require multiple clicks as each press of backspace on each color value will close the pop-up and each new entery of a value will also close the pop-up.
![Screenshot 2024-04-24 at 11 25 43 AM](https://github.com/wizzomafizzo/tapto/assets/32771064/9ce1e897-cf0a-458e-b90c-3c70f764f1c6)

**Comment by asturur** [comment]
Hey @TheTrainGoes not sure if this board is correct for the  tapto-designer bugs. i Don't monitor it if not pinged by @wizzomafizzo.

I'm ok focusing all the bugs in a single boards, but i didn't see this for 3 weeks

**Comment by asturur** [comment]
So the bug is that after any press, if wha you typed is a valid color, the popup will close. So moving from 255,255,255 to 255,255,25 is valid and the popup will close.

Yeah it is terrible

**Comment by asturur** [comment]
fixed via https://github.com/asturur/nfc-retro-label-printer/pull/33
