### ISSUE TITLE
Support for CCID USB readers

### ISSUE THREAD

**Issue by drebes** [wizzomafizzo/tapto#60]
I have a Sony CCID based NFC reader. Being CCID, it is supported by libnfc (as of 1.8.0) if libnfc is compiled with the pcsc driver (`./configure --with-drivers=all` since by default the `pcsc` is not included in the default driver list)

Would it be possible to include the PCSC driver to support CCID based readers like this?

**Comment by drebes** [comment]
I just saw wizzomafizzo/tapto#4 which I is related. As noted above there's a driver for pcsc in libnfc but it's not compiled by default. When using that driver there's no need for a connection string.

**Comment by wizzomafizzo** [comment]
Hi. I have not been able to compile libnfc successfully myself with pcsc enabled, for some reason it will not link to libpcsclite. I've attached a version of tapto compiled against the stock libnfc in ubuntu, which I *think* includes pcsc support. You're welcome to try it out! I haven't had much luck with it myself

[tapto-ubuntu-libnfc.zip](https://github.com/wizzomafizzo/tapto/files/15430094/tapto-ubuntu-libnfc.zip)

**Comment by drebes** [comment]
Thanks, I'll give it a try. I'll try to setup an environment to try to compile it myself but that may take a bit longer.

**Comment by drebes** [comment]
I think I'm having issues with libnfc and this reader. While it detects the reader it has trouble reading cards. I'll close this for now and reopen once I have sorted this out.
